@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Andre Luiz",
  "email": "admin@adventure.dev.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
   "email": "admin@adventure.dev.br",
  "password": "123456"
}


###

# @name create_task
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "sivaldo",
  "description": "This is a description of the new task",
  "status": "pending",
  "priority": "medium"
}


###

# @name list_tasks
GET  {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name delete_tasks
DELETE {{baseUrl}}/tasks/0bd7ba2b-fdee-4063-8c9f-22864a1a6ff9
Content-Type: application/json
Authorization: Bearer {{authToken}}