version: '3.8'

services:
  mysql:
    container_name: nest-clean-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: nest-clean
    volumes:
      - ./data/mysql:/var/lib/mysql
